-- Run this once in the Supabase dashboard's SQL Editor (Phase 6 setup).
-- Creates the per-user, human-browsable conversation transcript log.
-- Separate from Pinecone's conversation-memory namespace, which is the
-- AI's own fuzzy, by-meaning recall — this is the exact, ordered record.

create table conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table conversations enable row level security;

-- Without this, our backend's service_role key gets "permission denied
-- for table conversations" on every insert — enabling RLS above doesn't
-- grant table-level access by itself, it only controls what RLS *policies*
-- would apply if service_role weren't bypassing them.
grant select, insert on public.conversations to service_role;
